using System;
using System.Collections.Generic;

namespace InstantAIGate.Application.Dtos.Requests
{
    /// <summary>
    /// Represents a single message in a chat conversation.
    /// Supports multiple roles (system, user, assistant, tool) and various content types
    /// including plain text and function/tool calls for advanced conversational patterns.
    /// </summary>
    public record ChatMessage
    {
        /// <summary>
        /// The role of the message author. Can be "system", "user", "assistant", or "tool".
        /// Determines how the model interprets and responds to the message content.
        /// System messages provide high-level instructions, user messages are human inputs,
        /// assistant messages are model responses, and tool messages return function results.
        /// </summary>
        public string Role { get; init; } = "user";

        /// <summary>
        /// The textual content of the message.
        /// For user and system messages, this contains the prompt or instruction.
        /// For assistant messages, this contains the model's generated response.
        /// For tool messages, this contains the function call result.
        /// Can be null for assistant messages that only contain tool calls.
        /// </summary>
        public string Content { get; init; } = "";

        /// <summary>
        /// Multimodal content parts (text, images, audio) for vision/audio models.
        /// Present when the message contains non-text content like images or audio.
        /// The text portions are also extracted into the Content property for compatibility.
        /// </summary>
        public List<ContentPart>? ContentParts { get; init; }


        /// <summary>
        /// An optional name for the message author (user or assistant).
        /// Helps distinguish between multiple participants in a conversation.
        /// Does not affect model behavior but provides context for message attribution.
        /// Must contain only alphanumeric characters and underscores.
        /// </summary>
        public string? Name { get; init; }

        /// <summary>
        /// The unique identifier of the tool call that this message is responding to.
        /// Required when Role is "tool" to correlate the response with the original function call.
        /// Must match the Id field of the corresponding ToolCall in the assistant message.
        /// Enables the model to understand which function result it's receiving.
        /// </summary>
        public string? ToolCallId { get; init; }

        /// <summary>
        /// List of tool calls generated by the assistant in this message.
        /// Present when the assistant decides to invoke one or more functions.
        /// Each ToolCall contains the function name and arguments as a JSON string.
        /// The application must execute these functions and return results as tool messages.
        /// Mutually exclusive with Content in most cases (either text or tool calls).
        /// </summary>
        public List<ToolCall>? ToolCalls { get; init; }
    }

    /// <summary>
    /// Represents a single tool (function) call generated by the assistant.
    /// Contains the function name and serialized arguments that the model wants to invoke.
    /// The application is responsible for executing the function and returning the result.
    /// </summary>
    public record ToolCall
    {
        /// <summary>
        /// The unique identifier for this tool call.
        /// Used to correlate the tool call with its corresponding result message.
        /// Must be passed back in the ToolCallId field of the tool response message.
        /// Generated by the model and should be treated as an opaque identifier.
        /// </summary>
        public string Id { get; init; } = string.Empty;

        /// <summary>
        /// The type of tool call. Currently only "function" is supported.
        /// Reserved for future extensibility to support other tool types.
        /// Should always be "function" for current OpenAI-compatible implementations.
        /// </summary>
        public string Type { get; init; } = "function";

        /// <summary>
        /// The function call details including name and arguments.
        /// Contains the specific function the model wants to invoke and its parameters.
        /// Arguments are provided as a JSON string that must be parsed before execution.
        /// </summary>
        public FunctionCall? Function { get; init; }
    }

    /// <summary>
    /// Contains the details of a function invocation requested by the model.
    /// Includes the function name and serialized arguments as a JSON string.
    /// </summary>
    public record FunctionCall
    {
        /// <summary>
        /// The name of the function to be called.
        /// Must match one of the function names defined in the Tools parameter of the request.
        /// Should be validated against the available functions before execution.
        /// </summary>
        public string Name { get; init; } = string.Empty;

        /// <summary>
        /// The arguments to pass to the function, serialized as a JSON string.
        /// Must be parsed using JSON deserialization before passing to the function.
        /// The structure should match the JSON Schema defined in the function's parameters.
        /// May be an empty object "{}" if the function takes no arguments.
        /// </summary>
        public string Arguments { get; init; } = "{}";
    }


    /// <summary>
    /// Represents a single content part in a multimodal message.
    /// </summary>
    public record ContentPart
    {
        /// <summary>
        /// The type of content part: "text", "image_url", or "input_audio".
        /// </summary>
        public string Type { get; init; } = "text";

        /// <summary>
        /// Text content (when Type is "text").
        /// </summary>
        public string? Text { get; init; }

        /// <summary>
        /// Image URL or base64 data (when Type is "image_url").
        /// </summary>
        public ImageContent? ImageUrl { get; init; }

        /// <summary>
        /// Audio data (when Type is "input_audio").
        /// </summary>
        public AudioContent? InputAudio { get; init; }
    }

    /// <summary>
    /// Represents image content in a multimodal message.
    /// </summary>
    public record ImageContent
    {
        /// <summary>
        /// The URL or base64-encoded image data.
        /// </summary>
        public string Url { get; init; } = string.Empty;

        /// <summary>
        /// The detail level: "low", "high", or "auto".
        /// </summary>
        public string? Detail { get; init; }
    }

    /// <summary>
    /// Represents audio content in a multimodal message.
    /// </summary>
    public record AudioContent
    {
        /// <summary>
        /// Base64-encoded audio data.
        /// </summary>
        public string Data { get; init; } = string.Empty;

        /// <summary>
        /// Audio format: "wav", "mp3", etc.
        /// </summary>
        public string Format { get; init; } = "wav";
    }
}