using InstantAIGate.Application.Dtos.Requests;
using InstantAIGate.Application.Interfaces.Inference;
using InstantAIGate.Application.Interfaces.Storage;
using InstantAIGate.Infrastructure.Templates;
using InstantAIGate.Infrastructure.Inference.Native;
using Microsoft.Extensions.Logging;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Text;

namespace InstantAIGate.Infrastructure.Inference.Adapters
{
    /// <summary>
    /// Chat adapter that uses LLaMA models for text generation.
    /// Fully isolated from native P/Invoke calls through INativeLlamaApi.
    /// Supports both streaming and non-streaming inference with configurable sampling parameters.
    /// </summary>
    public class LlamaChatAdapter : IChatAdapter
    {
        private readonly ILlamaModelManager _modelManager;
        private readonly IModelPathProvider _pathProvider;
        private readonly ILogger<LlamaChatAdapter> _logger;
        private readonly INativeLlamaApi _nativeApi;

        /// <summary>
        /// Initializes a new instance of the LlamaChatAdapter with required dependencies.
        /// </summary>
        /// <param name="modelManager">Manager for acquiring and releasing model instances.</param>
        /// <param name="pathProvider">Provider for resolving model file paths from model identifiers.</param>
        /// <param name="nativeApi">Abstraction layer over native llama.cpp P/Invoke calls.</param>
        /// <param name="logger">Logger instance for diagnostic and error reporting.</param>
        public LlamaChatAdapter(
            ILlamaModelManager modelManager,
            IModelPathProvider pathProvider,
            INativeLlamaApi nativeApi,
            ILogger<LlamaChatAdapter> logger)
        {
            _modelManager = modelManager;
            _pathProvider = pathProvider;
            _nativeApi = nativeApi;
            _logger = logger;
        }

        /// <summary>
        /// Generates a complete response synchronously by consuming the streaming output.
        /// Collects all tokens from StreamAsync and returns the final concatenated text.
        /// </summary>
        /// <param name="request">The chat request containing model, messages, and sampling parameters.</param>
        /// <param name="ct">Cancellation token to abort the generation process.</param>
        /// <returns>The complete generated text response.</returns>
        public async Task<string> GenerateAsync(LlamaChatRequest request, CancellationToken ct = default)
        {
            var sb = new StringBuilder();
            await foreach (var token in StreamAsync(request, ct))
            {
                sb.Append(token);
            }
            return sb.ToString();
        }

        /// <summary>
        /// Streams generated tokens asynchronously using Server-Sent Events pattern.
        /// Yields each decoded token as it is generated by the model.
        /// Supports configurable sampling parameters and smart context trimming (Sliding Window).
        /// </summary>
        /// <param name="request">The chat request containing model, messages, and sampling parameters.</param>
        /// <param name="ct">Cancellation token to abort the generation process.</param>
        /// <returns>An async enumerable of string tokens representing the generated text.</returns>
        public async IAsyncEnumerable<string> StreamAsync(LlamaChatRequest request, [EnumeratorCancellation] CancellationToken ct = default)
        {
            if (string.IsNullOrWhiteSpace(request.Model))
                throw new ArgumentException("Model identifier is required.");

            string resolvedPath = await _pathProvider.GetFullModelPathAsync(request.Model);
            var profile = ModelProfileResolver.Resolve(resolvedPath);

            using var model = await _modelManager.AcquireModelAsync(request.Model, ct);
            using var context = await _modelManager.AcquireContextAsync(request.Model, ct);

            // ==========================================
            // CLEAN CONFIGURATION RETRIEVAL
            // ==========================================
            if (!_modelManager.ActiveModels.TryGetValue(request.Model, out var modelSettings))
            {
                throw new InvalidOperationException($"Configuration for model '{request.Model}' not found in active registry.");
            }

            int nBatchLimit = (int)modelSettings.BatchSize;
            if (nBatchLimit <= 0)
            {
                nBatchLimit = 512;
                _logger.LogWarning("Invalid BatchSize in settings for '{Model}'. Falling back to 512.", request.Model);
            }

            int contextLimit = (int)modelSettings.ContextSize;
            int maxTokens = request.MaxTokens > 0 ? request.MaxTokens : 512;

            // Calculate how many tokens we can actually use for the prompt
            int availableTokensForPrompt = contextLimit - maxTokens;

            if (availableTokensForPrompt <= 0)
            {
                throw new InvalidOperationException($"Invalid context configuration. Context limit ({contextLimit}) must be greater than max generation tokens ({maxTokens}).");
            }

            IntPtr vocab = _nativeApi.ModelGetVocab(model.Handle);
            IntPtr ctxHandle = context.Handle;

            // Initial prompt building
            string prompt = profile.Template.BuildPrompt(request.Messages);
            byte[] promptBytes = Encoding.UTF8.GetBytes(prompt);

            // Allocate an array large enough to hold the context limit safely
            int[] tokens = new int[contextLimit + maxTokens + 128];

            int nTokens = _nativeApi.Tokenize(
                vocab,
                prompt,
                promptBytes.Length,
                tokens,
                tokens.Length,
                false,
                true
            );

            if (nTokens < 0)
            {
                tokens = new int[-nTokens];
                nTokens = _nativeApi.Tokenize(vocab, prompt, promptBytes.Length, tokens, tokens.Length, false, true);
            }

            // ==========================================
            // SLIDING WINDOW & DYNAMIC TRUNCATION
            // ==========================================
            while (nTokens > availableTokensForPrompt)
            {
                // Step 1: Try to remove historical messages first (excluding system prompt and the current message)
                int oldestMessageIndex = -1;
                for (int i = 0; i < request.Messages.Count - 1; i++)
                {
                    if (request.Messages[i].Role != "system")
                    {
                        oldestMessageIndex = i;
                        break;
                    }
                }

                if (oldestMessageIndex != -1)
                {
                    _logger.LogDebug("Context overflow: {Tokens}/{Limit}. Trimming historical message at index {Index}.", nTokens, availableTokensForPrompt, oldestMessageIndex);
                    request.Messages.RemoveAt(oldestMessageIndex);
                }
                else
                {
                    // Step 2: No historical messages left. We must truncate the current (last) message.

                    // 1. Find the index instead of just the object
                    int lastMessageIndex = request.Messages.FindLastIndex(m => m.Role != "system");

                    if (lastMessageIndex == -1)
                    {
                        break; // Fallback exit
                    }

                    var lastMessage = request.Messages[lastMessageIndex];

                    if (string.IsNullOrWhiteSpace(lastMessage.Content))
                    {
                        break;
                    }

                    int excessTokens = nTokens - availableTokensForPrompt;
                    int charsToRemove = (int)(excessTokens * 4.5);

                    string truncatedContent;

                    if (charsToRemove >= lastMessage.Content.Length)
                    {
                        // Keep a minimal chunk from the end
                        int keepLength = Math.Max(lastMessage.Content.Length / 10, 100);
                        truncatedContent = "..." + lastMessage.Content.Substring(lastMessage.Content.Length - keepLength);
                    }
                    else
                    {
                        // Truncate from the beginning
                        truncatedContent = "..." + lastMessage.Content.Substring(charsToRemove);
                    }

                    // 2. Use 'with' expression to create a new record and replace it in the list
                    request.Messages[lastMessageIndex] = lastMessage with { Content = truncatedContent };

                    _logger.LogWarning("Context overflow: {Tokens}/{Limit}. Truncating the beginning of the last message.", nTokens, availableTokensForPrompt);
                }

                // Rebuild the prompt and re-tokenize
                prompt = profile.Template.BuildPrompt(request.Messages);
                promptBytes = Encoding.UTF8.GetBytes(prompt);

                nTokens = _nativeApi.Tokenize(vocab, prompt, promptBytes.Length, tokens, tokens.Length, false, true);

                // Handle buffer resize if tokenization requires it (though string is shrinking, keep for safety)
                if (nTokens < 0)
                {
                    tokens = new int[-nTokens];
                    nTokens = _nativeApi.Tokenize(vocab, prompt, promptBytes.Length, tokens, tokens.Length, false, true);
                }
            }

            if (nTokens > availableTokensForPrompt)
            {
                throw new InvalidOperationException($"Fatal error during context truncation. Tokens ({nTokens}) still exceed available window ({availableTokensForPrompt}).");
            }

            if (nTokens <= 0)
                throw new InvalidOperationException("Tokenization failed after context trimming.");

            var chainParams = _nativeApi.SamplerChainDefaultParams();
            IntPtr sampler = _nativeApi.SamplerChainInit(chainParams);

            // === SAMPLER CHAIN CONFIGURATION ===
            _nativeApi.SamplerChainAdd(sampler, _nativeApi.SamplerInitTopK(request.TopK));
            _nativeApi.SamplerChainAdd(sampler, _nativeApi.SamplerInitTopP(request.TopP, (nuint)1));

            float temperature = request.Temperature > 0 ? request.Temperature : 0.7f;
            _nativeApi.SamplerChainAdd(sampler, _nativeApi.SamplerInitTemp(temperature));

            uint seed = request.Seed.HasValue ? (uint)request.Seed.Value : (uint)Random.Shared.Next();
            _nativeApi.SamplerChainAdd(sampler, _nativeApi.SamplerInitDist(seed));

            IntPtr repetitionSampler = _nativeApi.SamplerInitRepetition(
                1.1f,
                request.FrequencyPenalty,
                request.PresencePenalty
            );

            if (repetitionSampler != IntPtr.Zero)
            {
                _nativeApi.SamplerChainAdd(sampler, repetitionSampler);
            }
            else
            {
                _logger.LogWarning("Repetition sampler creation failed. Penalties will not be applied.");
            }

            int eos = _nativeApi.VocabEos(vocab);
            int currentPos = 0;
            int generated = 0;

            // ==========================================
            // MEMORY ALLOCATION BASED ON MODEL BATCH SIZE
            // ==========================================
            int maxBatchSize = nBatchLimit;

            int[] batchTokens = new int[maxBatchSize];
            int[] batchPos = new int[maxBatchSize];
            int[] batchNSeq = new int[maxBatchSize];
            sbyte[] batchLogits = new sbyte[maxBatchSize];

            int seqIdValue = 0;
            GCHandle hSeqIdValue = GCHandle.Alloc(seqIdValue, GCHandleType.Pinned);
            IntPtr ptrSeqIdValue = hSeqIdValue.AddrOfPinnedObject();

            IntPtr[] seqIdPointers = new IntPtr[maxBatchSize];
            for (int i = 0; i < maxBatchSize; i++)
            {
                seqIdPointers[i] = ptrSeqIdValue;
            }

            GCHandle hTokens = GCHandle.Alloc(batchTokens, GCHandleType.Pinned);
            GCHandle hPos = GCHandle.Alloc(batchPos, GCHandleType.Pinned);
            GCHandle hNSeq = GCHandle.Alloc(batchNSeq, GCHandleType.Pinned);
            GCHandle hLogits = GCHandle.Alloc(batchLogits, GCHandleType.Pinned);
            GCHandle hSeqIdPtrs = GCHandle.Alloc(seqIdPointers, GCHandleType.Pinned);

            var utf8Decoder = Encoding.UTF8.GetDecoder();
            byte[] byteBuffer = new byte[256];
            char[] charBuffer = new char[512];
            var accumulatedText = new StringBuilder();

            try
            {
                // ==========================================
                // PHASE 1: PROMPT INGESTION (Chunking)
                // ==========================================
                int lastEvalBatchSize = 0;
                for (int i = 0; i < nTokens; i += nBatchLimit)
                {
                    ct.ThrowIfCancellationRequested();

                    int evalBatchSize = Math.Min(nTokens - i, nBatchLimit);
                    lastEvalBatchSize = evalBatchSize;

                    for (int j = 0; j < evalBatchSize; j++)
                    {
                        batchTokens[j] = tokens[i + j];
                        batchPos[j] = i + j;
                        batchNSeq[j] = 1;
                        // Logits are only required for the final token of the complete prompt
                        batchLogits[j] = (sbyte)((i + j == nTokens - 1) ? 1 : 0);
                    }

                    int result = _nativeApi.Decode(
                        ctxHandle,
                        evalBatchSize,
                        hTokens.AddrOfPinnedObject(),
                        hPos.AddrOfPinnedObject(),
                        hNSeq.AddrOfPinnedObject(),
                        hSeqIdPtrs.AddrOfPinnedObject(),
                        hLogits.AddrOfPinnedObject());

                    if (result != 0)
                    {
                        _logger.LogWarning("llama_decode returned error code during prompt eval: {Code}", result);
                        yield break;
                    }
                }

                currentPos = nTokens;

                // ==========================================
                // PHASE 2: TOKEN GENERATION LOOP
                // ==========================================
                while (generated < maxTokens)
                {
                    ct.ThrowIfCancellationRequested();
                    int logitIndex = 0;

                    if (generated == 0)
                    {
                        // First generation relies on the last evaluated chunk
                        logitIndex = lastEvalBatchSize - 1;
                    }
                    else
                    {
                        // Decode a single newly generated token
                        batchTokens[0] = tokens[nTokens + generated - 1];
                        batchPos[0] = currentPos++;
                        batchNSeq[0] = 1;
                        batchLogits[0] = 1;

                        int result = _nativeApi.Decode(
                            ctxHandle,
                            1,
                            hTokens.AddrOfPinnedObject(),
                            hPos.AddrOfPinnedObject(),
                            hNSeq.AddrOfPinnedObject(),
                            hSeqIdPtrs.AddrOfPinnedObject(),
                            hLogits.AddrOfPinnedObject());

                        if (result != 0)
                        {
                            _logger.LogWarning("llama_decode returned error code during generation: {Code}", result);
                            yield break;
                        }
                    }

                    int token = _nativeApi.SamplerSample(sampler, ctxHandle, logitIndex);

                    if (token == eos || token < 0)
                        yield break;

                    tokens[nTokens + generated] = token;
                    generated++;

                    int pieceSize = _nativeApi.TokenToPiece(vocab, token, byteBuffer, byteBuffer.Length, 0, false);

                    if (pieceSize > byteBuffer.Length)
                    {
                        byteBuffer = new byte[pieceSize];
                        pieceSize = _nativeApi.TokenToPiece(vocab, token, byteBuffer, byteBuffer.Length, 0, false);
                    }

                    if (pieceSize > 0)
                    {
                        int charsDecoded = utf8Decoder.GetChars(byteBuffer, 0, pieceSize, charBuffer, 0, flush: false);

                        if (charsDecoded > 0)
                        {
                            string piece = new string(charBuffer, 0, charsDecoded);
                            accumulatedText.Append(piece);

                            string currentText = accumulatedText.ToString();

                            // Check for EOS markers in generated text
                            if (currentText.Contains("<|im_end|>") || currentText.Contains("<|endoftext|>"))
                            {
                                yield break;
                            }

                            // Check for custom stop sequences from request
                            if (request.Stop != null && request.Stop.Count > 0)
                            {
                                bool stopSequenceFound = false;
                                foreach (var stopSeq in request.Stop)
                                {
                                    if (!string.IsNullOrEmpty(stopSeq) && currentText.Contains(stopSeq))
                                    {
                                        stopSequenceFound = true;
                                        break;
                                    }
                                }

                                if (stopSequenceFound)
                                {
                                    yield break;
                                }
                            }

                            yield return piece;
                        }
                    }
                }

                int finalChars = utf8Decoder.GetChars(byteBuffer, 0, 0, charBuffer, 0, flush: true);
                if (finalChars > 0)
                {
                    string finalPiece = new string(charBuffer, 0, finalChars);
                    yield return finalPiece;
                }
            }
            finally
            {
                _nativeApi.SamplerFree(sampler);

                hTokens.Free();
                hPos.Free();
                hNSeq.Free();
                hLogits.Free();
                hSeqIdPtrs.Free();
                hSeqIdValue.Free();
            }
        }
    }
}