using System.Text.Json.Serialization;

namespace InstantAIGate.API.Dtos
{
    /// <summary>
    /// Universal message in OpenAI format (used in requests and responses).
    /// Supports multiple roles, content types (text, multimodal), and function/tool calling patterns.
    /// </summary>
    public class OpenAiMessage
    {
        /// <summary>
        /// The role of the message author. Can be "system", "user", "assistant", or "tool".
        /// Determines how the model interprets and responds to the message content.
        /// System messages provide high-level instructions, user messages are human inputs,
        /// assistant messages are model responses, and tool messages return function results.
        /// </summary>
        [JsonPropertyName("role")]
        public string Role { get; set; } = "user";

        /// <summary>
        /// The content of the message. Can be a string for text-only messages or an array
        /// of content parts for multimodal messages (text, images, audio).
        /// For user messages, this contains the prompt or instruction.
        /// For assistant messages, this contains the model's generated response.
        /// For tool messages, this contains the function call result.
        /// Can be null for assistant messages that only contain tool calls.
        /// </summary>
        [JsonPropertyName("content")]
        public object? Content { get; set; }

        /// <summary>
        /// An optional name for the message author (user or assistant).
        /// Helps distinguish between multiple participants in a conversation.
        /// Does not affect model behavior but provides context for message attribution.
        /// Must contain only alphanumeric characters and underscores.
        /// </summary>
        [JsonPropertyName("name")]
        public string? Name { get; set; }

        /// <summary>
        /// The refusal message by the assistant, if the model declined to respond.
        /// Present when the model refuses to generate content due to safety or policy reasons.
        /// Provides transparency about why the model did not produce a standard response.
        /// Only applicable to assistant messages.
        /// </summary>
        [JsonPropertyName("refusal")]
        public string? Refusal { get; set; }

        /// <summary>
        /// The tool calls generated by the model in this assistant message.
        /// Each tool call contains the function name and arguments as a JSON string.
        /// The application must execute these functions and return results as tool messages.
        /// Mutually exclusive with Content in most cases (either text or tool calls).
        /// Only applicable to assistant messages.
        /// </summary>
        [JsonPropertyName("tool_calls")]
        public List<OpenAiToolCall>? ToolCalls { get; set; }

        /// <summary>
        /// The unique identifier of the tool call that this message is responding to.
        /// Required when Role is "tool" to correlate the response with the original function call.
        /// Must match the Id field of the corresponding ToolCall in the assistant message.
        /// Enables the model to understand which function result it's receiving.
        /// </summary>
        [JsonPropertyName("tool_call_id")]
        public string? ToolCallId { get; set; }

        /// <summary>
        /// Deprecated: The function call generated by the model (legacy function calling API).
        /// Replaced by ToolCalls in the newer tools API.
        /// Included for backward compatibility with older OpenAI API versions.
        /// Only applicable to assistant messages.
        /// </summary>
        [JsonPropertyName("function_call")]
        public OpenAiFunctionCall? FunctionCall { get; set; }

        /// <summary>
        /// Annotations for the message content, providing additional metadata.
        /// Can include citations, references, or other contextual information.
        /// Used by some models to provide source attribution or explanatory notes.
        /// Only applicable to certain model types and response formats.
        /// </summary>
        [JsonPropertyName("annotations")]
        public List<object>? Annotations { get; set; }
    }

    /// <summary>
    /// Represents a single tool (function) call generated by the assistant.
    /// Contains the function name and serialized arguments that the model wants to invoke.
    /// </summary>
    public class OpenAiToolCall
    {
        /// <summary>
        /// The unique identifier for this tool call.
        /// Used to correlate the tool call with its corresponding result message.
        /// Must be passed back in the ToolCallId field of the tool response message.
        /// Generated by the model and should be treated as an opaque identifier.
        /// </summary>
        [JsonPropertyName("id")]
        public string Id { get; set; } = string.Empty;

        /// <summary>
        /// The type of tool call. Currently only "function" is supported.
        /// Reserved for future extensibility to support other tool types.
        /// Should always be "function" for current OpenAI-compatible implementations.
        /// </summary>
        [JsonPropertyName("type")]
        public string Type { get; set; } = "function";

        /// <summary>
        /// The function call details including name and arguments.
        /// Contains the specific function the model wants to invoke and its parameters.
        /// Arguments are provided as a JSON string that must be parsed before execution.
        /// </summary>
        [JsonPropertyName("function")]
        public OpenAiFunctionCall? Function { get; set; }
    }

    /// <summary>
    /// Contains the details of a function invocation requested by the model.
    /// Includes the function name and serialized arguments as a JSON string.
    /// </summary>
    public class OpenAiFunctionCall
    {
        /// <summary>
        /// The name of the function to be called.
        /// Must match one of the function names defined in the Tools parameter of the request.
        /// Should be validated against the available functions before execution.
        /// </summary>
        [JsonPropertyName("name")]
        public string Name { get; set; } = string.Empty;

        /// <summary>
        /// The arguments to pass to the function, serialized as a JSON string.
        /// Must be parsed using JSON deserialization before passing to the function.
        /// The structure should match the JSON Schema defined in the function's parameters.
        /// May be an empty object "{}" if the function takes no arguments.
        /// </summary>
        [JsonPropertyName("arguments")]
        public string Arguments { get; set; } = "{}";
    }

    /// <summary>
    /// Represents a single content part in a multimodal message.
    /// Used when Content is an array instead of a simple string.
    /// Supports text, images, and audio content types for multimodal models.
    /// </summary>
    public class OpenAiContentPart
    {
        /// <summary>
        /// The type of content part. Can be "text", "image_url", or "input_audio".
        /// Determines which additional fields are present in the content part.
        /// Text parts contain plain text, image_url parts contain image data or URLs,
        /// and input_audio parts contain audio data for audio-capable models.
        /// </summary>
        [JsonPropertyName("type")]
        public string Type { get; set; } = "text";

        /// <summary>
        /// The text content of the message part.
        /// Only applicable when Type is "text".
        /// Contains the plain text portion of a multimodal message.
        /// </summary>
        [JsonPropertyName("text")]
        public string? Text { get; set; }

        /// <summary>
        /// The image URL or base64-encoded image data.
        /// Only applicable when Type is "image_url".
        /// Can be a URL string or a data URI with base64-encoded image.
        /// Supports various image formats including PNG, JPEG, GIF, and WebP.
        /// </summary>
        [JsonPropertyName("image_url")]
        public OpenAiImageUrl? ImageUrl { get; set; }

        /// <summary>
        /// The input audio data for audio-capable models.
        /// Only applicable when Type is "input_audio".
        /// Contains base64-encoded audio data and format information.
        /// Used for models that can process audio input directly.
        /// </summary>
        [JsonPropertyName("input_audio")]
        public OpenAiInputAudio? InputAudio { get; set; }
    }

    /// <summary>
    /// Represents an image URL or base64-encoded image data in a multimodal message.
    /// </summary>
    public class OpenAiImageUrl
    {
        /// <summary>
        /// The URL of the image or a data URI with base64-encoded image data.
        /// Can be an HTTP/HTTPS URL pointing to an image file.
        /// Can also be a data URI in the format "data:image/jpeg;base64,{base64_data}".
        /// The image will be processed by multimodal models that support vision capabilities.
        /// </summary>
        [JsonPropertyName("url")]
        public string Url { get; set; } = string.Empty;

        /// <summary>
        /// The detail level of the image processing. Can be "low", "high", or "auto".
        /// Controls the trade-off between processing speed and image understanding quality.
        /// "low" uses fewer tokens and processes faster, "high" uses more tokens for better accuracy.
        /// "auto" lets the model decide the appropriate detail level based on the image.
        /// Only applicable to certain multimodal models.
        /// </summary>
        [JsonPropertyName("detail")]
        public string? Detail { get; set; }
    }

    /// <summary>
    /// Represents input audio data for audio-capable models.
    /// </summary>
    public class OpenAiInputAudio
    {
        /// <summary>
        /// The base64-encoded audio data.
        /// Contains the raw audio bytes encoded as a base64 string.
        /// The audio will be processed by models that support audio input.
        /// </summary>
        [JsonPropertyName("data")]
        public string Data { get; set; } = string.Empty;

        /// <summary>
        /// The format of the audio data. Can be "wav", "mp3", or other supported formats.
        /// Specifies the audio codec and container format for proper decoding.
        /// The model must support the specified audio format for successful processing.
        /// </summary>
        [JsonPropertyName("format")]
        public string Format { get; set; } = "wav";
    }
}